In [1]:
import pandas as pd
import numpy as np

import plotly.express as px
import datetime
from datetime import datetime

In [2]:
players = pd.read_csv("player_tianmin_class.csv")

#games = pd.read_csv("games_tianmin_class.csv")

moves = pd.read_csv("move_tianmin_class.csv")

In [3]:
# first 10 columns of players table
players.iloc[:,:10].head(5)

,Unnamed: 0,username,urls,time_control,end_time,uuid,initial_setup,time_class,rules,white_rating
0,0,tianminlyu,https://www.chess.com/game/live/64303831489,600,1670565015,0c860a8f-7785-11ed-a76d-78ac4409ff3c,rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w ...,rapid,chess,2208
1,1,tianminlyu,https://www.chess.com/game/live/64497025159,300,1670758600,9c4d81e6-7946-11ed-a76d-78ac4409ff3c,rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w ...,blitz,chess,2110
2,2,tianminlyu,https://www.chess.com/game/live/64535569441,600,1670797779,7638de52-79a0-11ed-a664-78ac4409ff3c,rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w ...,rapid,chess,2085
3,3,tianminlyu,https://www.chess.com/game/live/64536785477,600,1670798270,6a2234a4-79a3-11ed-a664-78ac4409ff3c,rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w ...,rapid,chess,2106
4,4,tianminlyu,https://www.chess.com/game/live/64621963451,900+10,1670884116,895e3266-7a69-11ed-a664-78ac4409ff3c,rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w ...,rapid,chess,2081

In [4]:
players.iloc[:,10:20].head(5)

,white_username,black_rating,black_username,pgn,event,Site,Date,Round,Result,CurrentPosition
0,Aakarsh-IND,2101,tianminlyu,"[Event ""Live Chess""]\n[Site ""Chess.com""]\n[Dat...",Live Chess,Chess.com,2022.12.09,-,0-1,rnb1nrk1/pp4bp/2pp4/1PPPp1q1/4Pp2/2NB1p2/P3NBP...
1,dragomirradin,2106,tianminlyu,"[Event ""Live Chess""]\n[Site ""Chess.com""]\n[Dat...",Live Chess,Chess.com,2022.12.11,-,1/2-1/2,5kB1/5P2/8/4n2K/8/8/8/8 w - -
2,nuove,2112,tianminlyu,"[Event ""Live Chess""]\n[Site ""Chess.com""]\n[Dat...",Live Chess,Chess.com,2022.12.11,-,0-1,8/p5k1/1p5p/4q3/8/5Q1P/7K/8 w - -
3,tianminlyu,2285,nila26,"[Event ""Live Chess""]\n[Site ""Chess.com""]\n[Dat...",Live Chess,Chess.com,2022.12.11,-,0-1,3r2kr/pQ2Bppp/1p2p3/2pq4/8/5PP1/PP4KP/8 w - -
4,JammyRedRoo,2116,tianminlyu,"[Event ""Live Chess""]\n[Site ""Chess.com""]\n[Dat...",Live Chess,Chess.com,2022.12.12,-,0-1,5rk1/p5r1/bp2p1p1/3pPp1p/3P3R/2P1q3/PP3RPP/5BK...

In [5]:
players.iloc[:,20:30].head(5)

,ECO,ECOUrl,EndDate,EndTime,StartTime,Termination,Timezone,UTCDate,UTCTime,class
0,D70,https://www.chess.com/openings/Kings-Indian-De...,2022.12.09,05:50:15,05:48:14,tianminlyu won by resignation,UTC,2022.12.09,05:48:14,Teacher
1,E60,https://www.chess.com/openings/Kings-Indian-De...,2022.12.11,11:36:40,11:26:14,Game drawn by timeout vs insufficient material,UTC,2022.12.11,11:26:14,Teacher
2,E32,https://www.chess.com/openings/Nimzo-Indian-De...,2022.12.11,22:29:39,22:09:23,tianminlyu won on time,UTC,2022.12.11,22:09:23,Teacher
3,A05,https://www.chess.com/openings/Reti-Opening-Ki...,2022.12.11,22:37:50,22:30:31,nila26 won by resignation,UTC,2022.12.11,22:30:31,Teacher
4,A46,https://www.chess.com/openings/Indian-Game-Lon...,2022.12.12,22:28:36,22:08:46,tianminlyu won by resignation,UTC,2022.12.12,22:08:46,Teacher

In [6]:
players.iloc[:,30:40].head(5)

   player_rating            timestamp
0           2101  2022-12-09 05:50:15
1           2106  2022-12-11 11:36:40
2           2112  2022-12-11 22:29:39
3           2106  2022-12-11 22:37:50
4           2116  2022-12-12 22:28:36

In [7]:
moves.head()

,Unnamed: 0,uuid,move_number,white_move,black_move,white_time,black_time
0,0,0c860a8f-7785-11ed-a76d-78ac4409ff3c,1.0,d4,Nf6,0:10:00,0:09:57.2
1,1,0c860a8f-7785-11ed-a76d-78ac4409ff3c,2.0,c4,g6,0:09:59,0:09:53.9
2,2,0c860a8f-7785-11ed-a76d-78ac4409ff3c,3.0,f3,Bg7,0:09:58.1,0:09:51.7
3,3,0c860a8f-7785-11ed-a76d-78ac4409ff3c,4.0,e4,O-O,0:09:57.4,0:09:50.1
4,4,0c860a8f-7785-11ed-a76d-78ac4409ff3c,5.0,Nc3,d6,0:09:56.5,0:09:48.4

In [8]:
moves.loc[moves['uuid']=='0c860a8f-7785-11ed-a76d-78ac4409ff3c']

,Unnamed: 0,uuid,move_number,white_move,black_move,white_time,black_time
0,0,0c860a8f-7785-11ed-a76d-78ac4409ff3c,1.0,d4,Nf6,0:10:00,0:09:57.2
1,1,0c860a8f-7785-11ed-a76d-78ac4409ff3c,2.0,c4,g6,0:09:59,0:09:53.9
2,2,0c860a8f-7785-11ed-a76d-78ac4409ff3c,3.0,f3,Bg7,0:09:58.1,0:09:51.7
3,3,0c860a8f-7785-11ed-a76d-78ac4409ff3c,4.0,e4,O-O,0:09:57.4,0:09:50.1
4,4,0c860a8f-7785-11ed-a76d-78ac4409ff3c,5.0,Nc3,d6,0:09:56.5,0:09:48.4
5,5,0c860a8f-7785-11ed-a76d-78ac4409ff3c,6.0,Be3,e5,0:09:55.1,0:09:45.2
6,6,0c860a8f-7785-11ed-a76d-78ac4409ff3c,7.0,d5,Ne8,0:09:53.9,0:09:39.3
7,7,0c860a8f-7785-11ed-a76d-78ac4409ff3c,8.0,Bd3,f5,0:09:47.7,0:09:36.8
8,8,0c860a8f-7785-11ed-a76d-78ac4409ff3c,9.0,Nge2,c6,0:09:46.5,0:09:33.3
9,9,0c860a8f-7785-11ed-a76d-78ac4409ff3c,10.0,O-O,f4,0:09:41.7,0:09:32.1
10,10,0c860a8f-7785-11ed-a76d-78ac4409ff3c,11.0,Bf2,g5,0:09:40.3,0:09:19.5
11,11,0c860a8f-7785-11ed-a76d-78ac4409ff3c,12.0,b4,g4,0:09:33.5,0:09:14.4
12,12,0c860a8f-7785-11ed-a76d-78ac4409ff3c,13.0,c5,Qg5,0:09:29.7,0:09:06.1
13,13,0c860a8f-7785-11ed-a76d-78ac4409ff3c,14.0,b5,gxf3,0:09:17.4,0:08:58.3

In [9]:
# Q1 - how many games does this player play between date A and date B

# Q2 - What is the time of the week does this player play chess most often?

# Q3 - How many moves does this player have per game?

# Q4 - How much seconds does each move take for the player? ---

# Q5 - What is the most common opening when this player played white?

# Q6 - What is the most common opening when this player played black?

# Q7 - How does the rating change along the period?

# Q8 - How does the rating of its opponent along the period?

# Q9 - The distribution of type of games this player has played?

# 10 - win, lose, draw ratio

In [11]:
# timestamp UTC?
def period_games(username,period):
    """
    return the dataframe that contains the games the username has played during the period of time
    
    input: 
    
    username - username that belong to the target player
    period - a list contains two items, start date and the end date
    
    output:
    
    dataframe that contains the games the username has played during the period of time
    """
    start_date = datetime.date(datetime.strptime(period[0], '%m/%d/%y') )
    end_date = datetime.date(datetime.strptime(period[1], '%m/%d/%y') )
    
    
    usergame = players.loc[players['username'] == username]
    
    usergame['date'] = pd.to_datetime((usergame['timestamp']), errors='coerce').dt.date
    
    usergame = usergame.loc[(usergame.date >= start_date) & (usergame.date <= end_date) ]
    
    #usergame = usergame.groupby(['date']).nunique().reset_index()[['date','uuid']]

    #total_games = usergame['uuid'].sum()
    
    #fig = px.scatter(usergame, x='date', y='uuid', title="Number of games played by {}".format(username))
    #fig.show()
    return usergame
    

period_games('tianminlyu',['12/01/22','02/28/23'])

/var/folders/gm/sqkz8yg12_d12sb2rtq76mzw0000gn/T/ipykernel_11977/2762182756.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  usergame['date'] = pd.to_datetime((usergame['timestamp']), errors='coerce').dt.date

,Unnamed: 0,username,urls,time_control,end_time,uuid,initial_setup,time_class,rules,white_rating,...,EndTime,StartTime,Termination,Timezone,UTCDate,UTCTime,class,player_rating,timestamp,date
0,0,tianminlyu,https://www.chess.com/game/live/64303831489,600,1670565015,0c860a8f-7785-11ed-a76d-78ac4409ff3c,rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w ...,rapid,chess,2208,...,05:50:15,05:48:14,tianminlyu won by resignation,UTC,2022.12.09,05:48:14,Teacher,2101,2022-12-09 05:50:15,2022-12-09
1,1,tianminlyu,https://www.chess.com/game/live/64497025159,300,1670758600,9c4d81e6-7946-11ed-a76d-78ac4409ff3c,rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w ...,blitz,chess,2110,...,11:36:40,11:26:14,Game drawn by timeout vs insufficient material,UTC,2022.12.11,11:26:14,Teacher,2106,2022-12-11 11:36:40,2022-12-11
2,2,tianminlyu,https://www.chess.com/game/live/64535569441,600,1670797779,7638de52-79a0-11ed-a664-78ac4409ff3c,rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w ...,rapid,chess,2085,...,22:29:39,22:09:23,tianminlyu won on time,UTC,2022.12.11,22:09:23,Teacher,2112,2022-12-11 22:29:39,2022-12-11
3,3,tianminlyu,https://www.chess.com/game/live/64536785477,600,1670798270,6a2234a4-79a3-11ed-a664-78ac4409ff3c,rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w ...,rapid,chess,2106,...,22:37:50,22:30:31,nila26 won by resignation,UTC,2022.12.11,22:30:31,Teacher,2106,2022-12-11 22:37:50,2022-12-11
4,4,tianminlyu,https://www.chess.com/game/live/64621963451,900+10,1670884116,895e3266-7a69-11ed-a664-78ac4409ff3c,rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w ...,rapid,chess,2081,...,22:28:36,22:08:46,tianminlyu won by resignation,UTC,2022.12.12,22:08:46,Teacher,2116,2022-12-12 22:28:36,2022-12-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,161,tianminlyu,https://www.chess.com/game/live/68485960171,900+10,1674748491,e1c46f8a-9d8d-11ed-bcea-78ac4409ff3c,rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w ...,rapid,chess,1618,...,16:56:39,16:50:24,boii113 won by resignation,UTC,2023.01.27,16:50:24,Teacher,1945,2023-01-26 15:54:51,2023-01-26
162,162,tianminlyu,https://www.chess.com/game/live/68488286939,900+10,1674750205,2e2ce194-9d93-11ed-bcea-78ac4409ff3c,rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w ...,rapid,chess,1952,...,09:23:36,09:00:26,tianminlyu won by resignation,UTC,2023.02.01,09:00:26,Teacher,1952,2023-01-26 16:23:25,2023-01-26
163,163,tianminlyu,https://www.chess.com/game/live/68577295509,900+10,1674838599,adf966cb-9e62-11ed-ab9a-78ac4409ff3c,rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w ...,rapid,chess,1941,...,12:32:46,12:11:16,HiImNano won by resignation,UTC,2023.02.15,12:11:16,Teacher,1941,2023-01-27 16:56:39,2023-01-27
164,164,tianminlyu,https://www.chess.com/game/live/68981142153,900+10,1675243416,d38a958b-a20e-11ed-9668-78ac4409ff3c,rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w ...,rapid,chess,1957,...,15:06:47,14:19:20,tianminlyu won on time,UTC,2023.02.15,14:19:20,Teacher,1957,2023-02-01 09:23:36,2023-02-01
165,165,tianminlyu,https://www.chess.com/game/live/70202086741,900+10,1676464366,c9c63ddd-ad29-11ed-880b-78ac4409ff3c,rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w ...,rapid,chess,1839,...,08:38:45,18:41:40,tianminlyu won on time,UTC,2022.12.28,18:41:40,Teacher,1946,2023-02-15 12:32:46,2023-02-15

In [12]:
# Q1 - how many games does this player play between date A and date B
# timestamp UTC?
def number_games(username,period):
    """
    return the number of games that the username has played during the period of time
    
    input: 
    
    username - username that belong to the target player
    period - a list contains two items, start date and the end date
    
    output:
    number of games this username has played during the period
    """
    usergame = period_games(username,period)

    total_games = usergame['uuid'].nunique()
    
    return total_games
    #fig = px.scatter(usergame, x='date', y='uuid', title="Number of games played by {}".format(username))
    #fig.show()
    

number_games('tianminlyu',['12/01/22','02/28/23'])

/var/folders/gm/sqkz8yg12_d12sb2rtq76mzw0000gn/T/ipykernel_11977/2762182756.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  usergame['date'] = pd.to_datetime((usergame['timestamp']), errors='coerce').dt.date

166

In [13]:
# Q2 - What is the time of the week does this player play chess?

def play_time(username,period):
    """
    return a dataframe that shows game uuid, the date, hour, the username was playing during the period of time
    
    input: 
    
    username - username that belong to the target player
    period - a list contains two items, start date and the end date
    
    output:
    return a dataframe that shows how many games the date, hour, the username has played during the period of time
    """
    
    usergame = period_games(username,period)
    usergame_period = usergame[['username','timestamp','uuid']]
    usergame_period['dow'] = pd.to_datetime((usergame_period['timestamp']), errors='coerce').dt.day_name()
    usergame_period['hour'] = pd.to_datetime((usergame_period['timestamp']), errors='coerce').dt.hour
    
    game_dow = usergame_period.groupby(['dow']).nunique().reset_index()[['dow','uuid']]
    return game_dow
play_time('tianminlyu',['12/01/22','02/28/23'])

/var/folders/gm/sqkz8yg12_d12sb2rtq76mzw0000gn/T/ipykernel_11977/2762182756.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  usergame['date'] = pd.to_datetime((usergame['timestamp']), errors='coerce').dt.date
/var/folders/gm/sqkz8yg12_d12sb2rtq76mzw0000gn/T/ipykernel_11977/1476778634.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  usergame_period['dow'] = pd.to_datetime((usergame_period['timestamp']), errors='coerce').dt.day_name()
/var/folders/gm/sqkz8yg12_d12sb2rtq76mzw0000gn/T/ipykernel_11977/1476778634.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  usergame_period['hour'] = pd.to_datetime((usergame_period['timestamp']), errors='coerce').dt.hour

         dow  uuid
0     Friday    22
1     Monday    22
2   Saturday    43
3     Sunday    38
4   Thursday     5
5    Tuesday    25
6  Wednesday    11

In [14]:
# Q3 - How many moves does this player have per game?

def move_number(username, period):
    usergame = period_games(username,period)
    games_move = pd.merge(usergame, moves, on=["uuid"])

    move_aggr = games_move.groupby(['username','uuid']).max().reset_index()[['username','uuid','move_number']]
    avg_move = int(round(move_aggr['move_number'].sum() / move_aggr['uuid'].nunique(),0))
    return avg_move

move_number('tianminlyu',['12/01/22','02/28/23'])

/var/folders/gm/sqkz8yg12_d12sb2rtq76mzw0000gn/T/ipykernel_11977/2762182756.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  usergame['date'] = pd.to_datetime((usergame['timestamp']), errors='coerce').dt.date
/var/folders/gm/sqkz8yg12_d12sb2rtq76mzw0000gn/T/ipykernel_11977/1192480295.py:7: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  move_aggr = games_move.groupby(['username','uuid']).max().reset_index()[['username','uuid','move_number']]

31

In [27]:
# Q4 - How much seconds does each move take for the player?


def is_white_player(row):
    if row['username'].lower() == row['white_username'].lower():
        return 1
    else:
        return 0


def player_rating(row):  
    if row['username'].lower() == row['white_username'].lower():
        return row['white_rating']
    else:
        return row['black_rating']
    
def opponent_rating(row):  
    if row['username'].lower() == row['black_username'].lower():
        return row['white_rating']
    else:
        return row['black_rating']
    

def is_white_player(row):
    if row['username'].lower() == row['white_username'].lower():
        return 1
    else:
        return 0



def play_time(row):
    if row['is_white_player'] == 1:
        return row['white_time']
    else:
        return row['black_time']
    

def remain_time(row):
    if row['time_accre'] == None:
        return row['time_fixed']
    else:
        return float(row['time_fixed']) + float(row['time_accre']) * float(row['move_number'])
    


def remain_play_time(row):
    if type(row['play_time']) == float:
        return None
    else:
        return int(row['time_hour']) * 3600 + int(row['time_min']) * 60 + float(row['time_sec'])

def first_move_time(row):
    if row['move_number'] == 1:
        return row['time_spent']
    else:
        return row['move_time']

#move_time.loc[move_time['play_time'].isnull]

#move_time[move_time['play_time'].isnull()]
#move_number('AGcuber19',['12/01/22','02/28/23'])

def move_time(username, period):
    usergame = period_games(username,period)
    games_move = pd.merge(usergame, moves, on=["uuid"])
    games_move['is_white_player'] = games_move.apply(lambda row: is_white_player(row), axis=1)
    games_move['play_time'] = games_move.apply(lambda row: play_time(row), axis=1)
    move_time = games_move[['username','uuid','urls','time_control','move_number','play_time']]
    move_time[['time_fixed', 'time_accre']] = move_time.time_control.str.split("+", expand = True) # none row has +
    move_time['time_remain'] = move_time.apply(lambda row: remain_time(row), axis=1)
    move_time[['time_hour', 'time_min','time_sec']] = move_time.play_time.str.split(":", expand = True)
    move_time['play_time_remain'] = move_time.apply(lambda row: remain_play_time(row), axis=1)
    move_time['time_spent'] = move_time['time_remain'].astype(float) - move_time['play_time_remain'].astype(float)
    move_time['next_time_spent'] = move_time.groupby(['username','uuid'])['time_spent'].shift(1)
    move_time['move_time'] = move_time['time_spent'] - move_time['next_time_spent'] 
    move_time['move_time_full'] = move_time.apply(lambda row: first_move_time(row), axis=1)
    avg_time = round(move_time['move_time_full'].mean(),2)
    return move_time

move_time('tianminlyu',['12/01/22','02/28/23'])

/var/folders/gm/sqkz8yg12_d12sb2rtq76mzw0000gn/T/ipykernel_11977/2762182756.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  usergame['date'] = pd.to_datetime((usergame['timestamp']), errors='coerce').dt.date
/var/folders/gm/sqkz8yg12_d12sb2rtq76mzw0000gn/T/ipykernel_11977/3682535806.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  move_time['time_remain'] = move_time.apply(lambda row: remain_time(row), axis=1)
/var/folders/gm/sqkz8yg12_d12sb2rtq76mzw0000gn/T/ipykernel_11977/3682535806.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  move_time['play_time_remain'] = move_time.apply(lambda row: remain_play_time(row), axis=1)
/var/folders/gm/sqkz8yg12_d12sb2rtq76mzw0000gn/T/ipykernel_11977/3682535806.py:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  move_time['time_spent'] = move_time['time_remain'].astype(float) - move_time['play_time_remain'].astype(float)
/var/folders/gm/sqkz8yg12_d12sb2rtq76mzw0000gn/T/ipykernel_11977/3682535806.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  move_time['next_time_spent'] = move_time.groupby(['username','uuid'])['time_spent'].shift(1)
/var/folders/gm/sqkz8yg12_d12sb2rtq76mzw0000gn/T/ipykernel_11977/3682535806.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  move_time['move_time'] = move_time['time_spent'] - move_time['next_time_spent']
/var/folders/gm/sqkz8yg12_d12sb2rtq76mzw0000gn/T/ipykernel_11977/3682535806.py:77: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  move_time['move_time_full'] = move_time.apply(lambda row: first_move_time(row), axis=1)

,username,uuid,urls,time_control,move_number,play_time,time_fixed,time_accre,time_remain,time_hour,time_min,time_sec,play_time_remain,time_spent,next_time_spent,move_time,move_time_full
0,tianminlyu,0c860a8f-7785-11ed-a76d-78ac4409ff3c,https://www.chess.com/game/live/64303831489,600,1.0,0:09:57.2,600,None,600,0,09,57.2,597.2,2.8,NaN,NaN,2.8
1,tianminlyu,0c860a8f-7785-11ed-a76d-78ac4409ff3c,https://www.chess.com/game/live/64303831489,600,2.0,0:09:53.9,600,None,600,0,09,53.9,593.9,6.1,2.8,3.3,3.3
2,tianminlyu,0c860a8f-7785-11ed-a76d-78ac4409ff3c,https://www.chess.com/game/live/64303831489,600,3.0,0:09:51.7,600,None,600,0,09,51.7,591.7,8.3,6.1,2.2,2.2
3,tianminlyu,0c860a8f-7785-11ed-a76d-78ac4409ff3c,https://www.chess.com/game/live/64303831489,600,4.0,0:09:50.1,600,None,600,0,09,50.1,590.1,9.9,8.3,1.6,1.6
4,tianminlyu,0c860a8f-7785-11ed-a76d-78ac4409ff3c,https://www.chess.com/game/live/64303831489,600,5.0,0:09:48.4,600,None,600,0,09,48.4,588.4,11.6,9.9,1.7,1.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5579,tianminlyu,c9c63ddd-ad29-11ed-880b-78ac4409ff3c,https://www.chess.com/game/live/70202086741,900+10,41.0,0:11:49.7,900,10,1310.0,0,11,49.7,709.7,600.3,591.7,8.6,8.6
5580,tianminlyu,c9c63ddd-ad29-11ed-880b-78ac4409ff3c,https://www.chess.com/game/live/70202086741,900+10,42.0,0:11:57.9,900,10,1320.0,0,11,57.9,717.9,602.1,600.3,1.8,1.8
5581,tianminlyu,c9c63ddd-ad29-11ed-880b-78ac4409ff3c,https://www.chess.com/game/live/70202086741,900+10,43.0,0:11:56.8,900,10,1330.0,0,11,56.8,716.8,613.2,602.1,11.1,11.1
5582,tianminlyu,c9c63ddd-ad29-11ed-880b-78ac4409ff3c,https://www.chess.com/game/live/70202086741,900+10,44.0,0:11:57.2,900,10,1340.0,0,11,57.2,717.2,622.8,613.2,9.6,9.6
5583,tianminlyu,c9c63ddd-ad29-11ed-880b-78ac4409ff3c,https://www.chess.com/game/live/70202086741,900+10,45.0,NaN,900,10,1350.0,NaN,NaN,NaN,NaN,NaN,622.8,NaN,NaN

In [28]:
# Q5 - What is the most common opening when this player played white?


def white_opening(username, period, top):
    usergame = period_games(username,period)
    games_move = pd.merge(usergame, moves, on=["uuid"])
    games_move['is_white_player'] = games_move.apply(lambda row: is_white_player(row), axis=1)

    games_move = games_move.loc[games_move['is_white_player'] == 1]
    move_aggr = games_move.groupby(['username','ECO']).nunique().reset_index()[['username','ECO','uuid']].sort_values(by =
                                                                                                                     'uuid', ascending = False)
    
    return move_aggr.head(top)

white_opening('tianminlyu',['12/01/22','02/28/23'],5)

/var/folders/gm/sqkz8yg12_d12sb2rtq76mzw0000gn/T/ipykernel_11977/2762182756.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  usergame['date'] = pd.to_datetime((usergame['timestamp']), errors='coerce').dt.date

      username  ECO  uuid
3   tianminlyu  A07     9
2   tianminlyu  A05     6
1   tianminlyu  A04     6
6   tianminlyu  A45     4
19  tianminlyu  C00     4

In [29]:
# Q6 - What is the most common opening when this player played black?


def black_opening(username, period, top):
    usergame = period_games(username,period)
    games_move = pd.merge(usergame, moves, on=["uuid"])
    games_move['is_white_player'] = games_move.apply(lambda row: is_white_player(row), axis=1)

    games_move = games_move.loc[games_move['is_white_player'] == 0]
    move_aggr = games_move.groupby(['username','ECO']).nunique().reset_index()[['username','ECO','uuid']].sort_values(by =
                                                                                                                     'uuid', ascending = False)
    
    return move_aggr.head(top)

black_opening('tianminlyu',['12/01/22','02/28/23'],5)

/var/folders/gm/sqkz8yg12_d12sb2rtq76mzw0000gn/T/ipykernel_11977/2762182756.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  usergame['date'] = pd.to_datetime((usergame['timestamp']), errors='coerce').dt.date

      username  ECO  uuid
4   tianminlyu  A07    13
12  tianminlyu  B00     7
2   tianminlyu  A04     6
14  tianminlyu  B20     4
29  tianminlyu  C50     4

In [30]:
# Q7 - How does the rating change along the period?

def rating_overtime(username,period,ascending = True):
    usergames = players.loc[players['username'] == username]
    rating_time = usergames[['username','time_class','timestamp','uuid','player_rating']].sort_values(by = 'timestamp',ascending = ascending)
    avg_rating = rating_time.groupby(['username','time_class']).mean().reset_index()[['username','time_class','player_rating']]
    return rating_time, avg_rating
rating_overtime('tianminlyu',['12/01/22','02/28/23'], False)[1]

     username time_class  player_rating
0  tianminlyu      blitz    2084.076923
1  tianminlyu      rapid    1935.322835

In [31]:
# Q8 - How does the rating of its opponent along the period?
def opponent_rating_time(username,period,ascending = True):
    usergames = players.loc[players['username'] == username]
    usergames['opponent_rating'] = usergames.apply(lambda row: opponent_rating(row), axis=1)
    opponent_rating_time = usergames[['username','time_class','timestamp','opponent_rating']].sort_values(by = 'timestamp',ascending = ascending)
    avg_rating = opponent_rating_time.groupby(['username','time_class']).mean().reset_index()[['username','time_class','opponent_rating']]

    return opponent_rating_time, avg_rating

opponent_rating_time('tianminlyu',['12/01/22','02/28/23'], False)[1]

/var/folders/gm/sqkz8yg12_d12sb2rtq76mzw0000gn/T/ipykernel_11977/2982505385.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  usergames['opponent_rating'] = usergames.apply(lambda row: opponent_rating(row), axis=1)

     username time_class  opponent_rating
0  tianminlyu      blitz      1855.948718
1  tianminlyu      rapid      1283.220472

In [32]:
# Q9 - The distribution of type of games this player has played?

def time_control(username,period):
    usergames = players.loc[players['username'] == username]
    user_time_control = usergames.groupby(['username','time_control']).nunique().reset_index()[['username','time_control','uuid']]
    return user_time_control

time_control('tianminlyu',['12/01/22','02/28/23'])

     username time_control  uuid
0  tianminlyu        180+2    22
1  tianminlyu         1800     4
2  tianminlyu          300    17
3  tianminlyu          600    23
4  tianminlyu       900+10   100

In [33]:
#10 - win, lose, draw ratio
def result_outcome(username,period):
    usergames = players.loc[players['username'] == username]
    usergames['is_white_player'] = usergames.apply(lambda row: is_white_player(row), axis=1)

    outcome = usergames.groupby(['username','Result','is_white_player']).nunique().reset_index()[['username',
                                                                                                 'Result',
                                                                                                  'is_white_player',
                                                                                                 'uuid']]
    
    return outcome
result_outcome('tianminlyu',['12/01/22','02/28/23'])

/var/folders/gm/sqkz8yg12_d12sb2rtq76mzw0000gn/T/ipykernel_11977/122488857.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  usergames['is_white_player'] = usergames.apply(lambda row: is_white_player(row), axis=1)

     username   Result  is_white_player  uuid
0  tianminlyu      0-1                0    53
1  tianminlyu      0-1                1    28
2  tianminlyu      1-0                0    33
3  tianminlyu      1-0                1    48
4  tianminlyu  1/2-1/2                0     3
5  tianminlyu  1/2-1/2                1     1

In [34]:
"""
你好，{username}! 这是你的期中学习报告 --

本学期从{start date} 到 {end date}，你在chess.com上下了{number of games} 盘棋。其中最多的一天是在 {日期}，你下了 {number}盘棋。

在所有棋局中，你赢了。。。盘，输了。。。盘，和了。。。盘

你最喜欢的计时方式是 。。。，你下了 。。。这样的对局。

# 你的对局平均时长在 。。。秒，你平均每步棋需要。。。秒，和班里的其他同学相比，你比平均时长快/慢 。 你是一个 。。。

你在这期间的chess.com的rapid平均积分为 。。。，你的对手平均积分为 。。。

相信在未来你会遇到更厉害的对手，你的国际象棋水平也会越来越高！
"""

'\n你好，{username}! 这是你的期中学习报告 --\n\n本学期从{start date} 到 {end date}，你在chess.com上下了{number of games} 盘棋。其中最多的一天是在 {日期}，你下了 {number}盘棋。\n\n在所有棋局中，你赢了。。。盘，输了。。。盘，和了。。。盘\n\n你最喜欢的计时方式是 。。。，你下了 。。。这样的对局。\n\n# 你的对局平均时长在 。。。秒，你平均每步棋需要。。。秒，和班里的其他同学相比，你比平均时长快/慢 。 你是一个 。。。\n\n你在这期间的chess.com的rapid平均积分为 。。。，你的对手平均积分为 。。。\n\n相信在未来你会遇到更厉害的对手，你的国际象棋水平也会越来越高！\n'

In [35]:
def user_report(username,period):
    start_date = period[0]
    end_date = period[1]
    number_game = number_games(username,period)
    move_numbers = move_number(username,period)
    avg_move_time = round(move_time(username,period)['move_time_full'].mean(),2)
    max_move = move_time(username,period).sort_values(by = ['move_time_full'], ascending = False)
    max_move_url = max_move['urls'].iloc[0]
    max_move_number = int(max_move['move_number'].iloc[0])
    max_move_time = int(max_move['move_time_full'].iloc[0])

    return start_date, end_date, username, number_game, move_numbers, avg_move_time, \
max_move_url, max_move_number, max_move_time
    
result =  user_report('tianminlyu',['12/01/22','02/28/23'])
   
text = "Hi，{}，在这学期中，从{}到 {}，你一共下了{}盘棋。在这些对局中，你平均走了{}步，平均每步用时{}秒。其中这盘棋 （{}）的第{}步，花了你{} 秒思考时间，是本学期你思考最长的一步棋。"  \
.format(result[2], 
        result[0], 
        result[1], 
        result[3],
        result[4],
        result[5], 
        result[6], 
        result[7],
        result[8])

for user in players['username'].unique():
    #print(user)
    try:
        result = user_report(user,['12/01/22','02/28/23'])
        text = "Hi，{}，在这学期中，从{}到 {}，你一共下了{}盘棋。\
        在这些对局中，你平均走了{}步，平均每步用时{}秒。其中这盘棋 （{}）的第{}步，\
        花了你{} 秒思考时间，是本学期你思考最长的一步棋。"  \
.format(result[2], 
        result[0], 
        result[1], 
        result[3],
        result[4],
        result[5], 
        result[6], 
        result[7],
        result[8])
        print(text)
        print("------")
    except:
        pass

/var/folders/gm/sqkz8yg12_d12sb2rtq76mzw0000gn/T/ipykernel_11977/2762182756.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  usergame['date'] = pd.to_datetime((usergame['timestamp']), errors='coerce').dt.date
/var/folders/gm/sqkz8yg12_d12sb2rtq76mzw0000gn/T/ipykernel_11977/1192480295.py:7: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  move_aggr = games_move.groupby(['username','uuid']).max().reset_index()[['username','uuid','move_number']]
/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py:3641: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
/var/folders/gm/sqkz8yg12_d12sb2rtq76mzw0000gn/T/ipykernel_11977/3682535806.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  move_time['time_remain'] = move_time.apply(lambda row: remain_time(row), axis=1)
/var/folders/gm/sqkz8yg12_d12sb2rtq76mzw0000gn/T/ipykernel_11977/3682535806.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  move_time['play_time_remain'] = move_time.apply(lambda row: remain_play_time(row), axis=1)
/var/folders/gm/sqkz8yg12_d12sb2rtq76mzw0000gn/T/ipykernel_11977/3682535806.py:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  move_time['time_spent'] = move_time['time_remain'].astype(float) - move_time['play_time_remain'].astype(float)
/var/folders/gm/sqkz8yg12_d12sb2rtq76mzw0000gn/T/ipykernel_11977/3682535806.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  move_time['next_time_spent'] = move_time.groupby(['username','uuid'])['time_spent'].shift(1)
/var/folders/gm/sqkz8yg12_d12sb2rtq76mzw0000gn/T/ipykernel_11977/3682535806.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  move_time['move_time'] = move_time['time_spent'] - move_time['next_time_spent']
/var/folders/gm/sqkz8yg12_d12sb2rtq76mzw0000gn/T/ipykernel_11977/3682535806.py:77: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  move_time['move_time_full'] = move_time.apply(lambda row: first_move_time(row), axis=1)

Hi，tianminlyu，在这学期中，从12/01/22到 02/28/23，你一共下了166盘棋。        在这些对局中，你平均走了31步，平均每步用时9.37秒。其中这盘棋 （https://www.chess.com/game/live/65029359353）的第16步，        花了你522 秒思考时间，是本学期你思考最长的一步棋。
------
Hi，xiaoanwu，在这学期中，从12/01/22到 02/28/23，你一共下了10盘棋。        在这些对局中，你平均走了39步，平均每步用时9.97秒。其中这盘棋 （https://www.chess.com/game/live/69265564609）的第43步，        花了你87 秒思考时间，是本学期你思考最长的一步棋。
------
Hi，EmmaXLi，在这学期中，从12/01/22到 02/28/23，你一共下了26盘棋。        在这些对局中，你平均走了36步，平均每步用时22.35秒。其中这盘棋 （https://www.chess.com/game/live/63928165113）的第1步，        花了你296 秒思考时间，是本学期你思考最长的一步棋。
------
Hi，akfunchess66，在这学期中，从12/01/22到 02/28/23，你一共下了24盘棋。        在这些对局中，你平均走了35步，平均每步用时6.92秒。其中这盘棋 （https://www.chess.com/game/live/66531143035）的第27步，        花了你77 秒思考时间，是本学期你思考最长的一步棋。
------
Hi，Marsboom，在这学期中，从12/01/22到 02/28/23，你一共下了69盘棋。        在这些对局中，你平均走了26步，平均每步用时13.54秒。其中这盘棋 （https://www.chess.com/game/live/69973571019）的第6步，        花了你348 秒思考时间，是本学期你思考最长的一步棋。
------
Hi，Claraqiu，在这学期中，从12/01/22到 02/28/23，你一共下了41盘棋。        在这些对局中，你平均走了27步，平均每步用时18.75秒。其中这盘棋 （https://www.chess.com/game/live/70474979353）的第22步，        花了你254 秒思考时间，是本学期你思考最长的一步棋。
------
Hi，Zora_zhu，在这学期中，从12/01/22到 02/28/23，你一共下了44盘棋。        在这些对局中，你平均走了31步，平均每步用时10.4秒。其中这盘棋 （https://www.chess.com/game/live/67554652835）的第14步，        花了你155 秒思考时间，是本学期你思考最长的一步棋。
------
Hi，BurleyWalrus，在这学期中，从12/01/22到 02/28/23，你一共下了26盘棋。        在这些对局中，你平均走了29步，平均每步用时9.46秒。其中这盘棋 （https://www.chess.com/game/live/70496596645）的第1步，        花了你152 秒思考时间，是本学期你思考最长的一步棋。
------
Hi，taionemm，在这学期中，从12/01/22到 02/28/23，你一共下了87盘棋。        在这些对局中，你平均走了29步，平均每步用时9.07秒。其中这盘棋 （https://www.chess.com/game/live/68771652735）的第16步，        花了你161 秒思考时间，是本学期你思考最长的一步棋。
------
Hi，augustinewz，在这学期中，从12/01/22到 02/28/23，你一共下了23盘棋。        在这些对局中，你平均走了30步，平均每步用时15.03秒。其中这盘棋 （https://www.chess.com/game/live/64430515181）的第32步，        花了你95 秒思考时间，是本学期你思考最长的一步棋。
------
Hi，oscarzhang818，在这学期中，从12/01/22到 02/28/23，你一共下了12盘棋。        在这些对局中，你平均走了29步，平均每步用时16.74秒。其中这盘棋 （https://www.chess.com/game/live/70479100309）的第15步，        花了你93 秒思考时间，是本学期你思考最长的一步棋。
------
Hi，yaohengli，在这学期中，从12/01/22到 02/28/23，你一共下了70盘棋。        在这些对局中，你平均走了27步，平均每步用时13.58秒。其中这盘棋 （https://www.chess.com/game/live/68169709527）的第10步，        花了你228 秒思考时间，是本学期你思考最长的一步棋。
------
Hi，Wallacewang1214，在这学期中，从12/01/22到 02/28/23，你一共下了41盘棋。        在这些对局中，你平均走了27步，平均每步用时8.91秒。其中这盘棋 （https://www.chess.com/game/live/68664714359）的第5步，        花了你126 秒思考时间，是本学期你思考最长的一步棋。
------
Hi，SophiaZ2022，在这学期中，从12/01/22到 02/28/23，你一共下了10盘棋。        在这些对局中，你平均走了51步，平均每步用时8.32秒。其中这盘棋 （https://www.chess.com/game/live/66850245621）的第26步，        花了你51 秒思考时间，是本学期你思考最长的一步棋。
------
Hi，yumitang，在这学期中，从12/01/22到 02/28/23，你一共下了9盘棋。        在这些对局中，你平均走了51步，平均每步用时18.35秒。其中这盘棋 （https://www.chess.com/game/live/67454646015）的第24步，        花了你248 秒思考时间，是本学期你思考最长的一步棋。
------
Hi，james2945，在这学期中，从12/01/22到 02/28/23，你一共下了37盘棋。        在这些对局中，你平均走了27步，平均每步用时16.51秒。其中这盘棋 （https://www.chess.com/game/live/65747016115）的第15步，        花了你236 秒思考时间，是本学期你思考最长的一步棋。
------
Hi，Oinkoinkw，在这学期中，从12/01/22到 02/28/23，你一共下了17盘棋。        在这些对局中，你平均走了38步，平均每步用时6.57秒。其中这盘棋 （https://www.chess.com/game/live/68664746585）的第24步，        花了你57 秒思考时间，是本学期你思考最长的一步棋。
------
Hi，Cathye1，在这学期中，从12/01/22到 02/28/23，你一共下了11盘棋。        在这些对局中，你平均走了21步，平均每步用时21.99秒。其中这盘棋 （https://www.chess.com/game/live/69904984295）的第32步，        花了你194 秒思考时间，是本学期你思考最长的一步棋。
------
Hi，lunathekitsune，在这学期中，从12/01/22到 02/28/23，你一共下了4盘棋。        在这些对局中，你平均走了26步，平均每步用时20.55秒。其中这盘棋 （https://www.chess.com/game/live/68669510989）的第22步，        花了你253 秒思考时间，是本学期你思考最长的一步棋。
------
Hi，ArthurRocket，在这学期中，从12/01/22到 02/28/23，你一共下了19盘棋。        在这些对局中，你平均走了30步，平均每步用时12.16秒。其中这盘棋 （https://www.chess.com/game/live/70491871849）的第1步，        花了你411 秒思考时间，是本学期你思考最长的一步棋。
------
Hi，vivianwwww20，在这学期中，从12/01/22到 02/28/23，你一共下了7盘棋。        在这些对局中，你平均走了30步，平均每步用时11.45秒。其中这盘棋 （https://www.chess.com/game/live/68676323617）的第6步，        花了你123 秒思考时间，是本学期你思考最长的一步棋。
------
Hi，ChloeWang16，在这学期中，从12/01/22到 02/28/23，你一共下了11盘棋。        在这些对局中，你平均走了23步，平均每步用时28.28秒。其中这盘棋 （https://www.chess.com/game/live/69276421703）的第5步，        花了你514 秒思考时间，是本学期你思考最长的一步棋。
------
Hi，ZhichengW，在这学期中，从12/01/22到 02/28/23，你一共下了12盘棋。        在这些对局中，你平均走了34步，平均每步用时9.8秒。其中这盘棋 （https://www.chess.com/game/live/69647023475）的第35步，        花了你108 秒思考时间，是本学期你思考最长的一步棋。
------
Hi，Haochen1123，在这学期中，从12/01/22到 02/28/23，你一共下了13盘棋。        在这些对局中，你平均走了31步，平均每步用时7.1秒。其中这盘棋 （https://www.chess.com/game/live/69473142295）的第10步，        花了你95 秒思考时间，是本学期你思考最长的一步棋。
------
Hi，jaydenlan0118，在这学期中，从12/01/22到 02/28/23，你一共下了6盘棋。        在这些对局中，你平均走了37步，平均每步用时11.14秒。其中这盘棋 （https://www.chess.com/game/live/69276421703）的第6步，        花了你72 秒思考时间，是本学期你思考最长的一步棋。
------
Hi，ImRacoonie，在这学期中，从12/01/22到 02/28/23，你一共下了7盘棋。        在这些对局中，你平均走了22步，平均每步用时10.17秒。其中这盘棋 （https://www.chess.com/game/live/70580108228）的第19步，        花了你49 秒思考时间，是本学期你思考最长的一步棋。
------

In [ ]:
"""
letters = ['a','b','c','d','e','f','g','h']
numbers = [1,2,3,4,5,6,7,8]

squares = []
for l in letters:
    for n in numbers:
        squares.append(l + str(n))
len(square)

squares[0]

letters.index('a')

letters[2]

def capture_square(color, piece, current_square):
    alphabet = current_square[0]
    alpha_index = letters.index(alphabet)
    number = int(current_square[1])
    caps = []
    for square in squares:
        square_alpha = square[0]
        square_number = int(square[1])
        if piece == 'p':
            if color == 'white' and ((square_alpha ==  letters[alpha_index + 1] or square_alpha ==  letters[alpha_index - 1]) and square_number == number + 1):
                caps.append(square)
            elif color == 'black' and ((square_alpha ==  letters[alpha_index + 1] or square_alpha ==  letters[alpha_index - 1]) and square_number == number - 1): 
                caps.append(square)
        elif piece == 'n' and ((square_alpha == letters[alpha_index + 1] and square_number == number + 2)  or \
                              (square_alpha == letters[alpha_index + 1] and square_number == number - 2) or   \
                              (square_alpha == letters[alpha_index + 2] and square_number == number - 1) or \
                              (square_alpha == letters[alpha_index + 2] and square_number == number + 1) or \
                              (square_alpha == letters[alpha_index - 2] and square_number == number + 1) or \
                              (square_alpha == letters[alpha_index - 2] and square_number == number - 1) or \
                              (square_alpha == letters[alpha_index - 1] and square_number == number + 2) or \
                              (square_alpha == letters[alpha_index - 1] and square_number == number - 2)): 
            caps.append(square)

            
            

                    
    return caps
            

capture_square("white",'p','a4')

test = 'b3'

alphabet = test[0]
alpha_index = letters.index(alphabet)
number = int(test[1])

letters[alpha_index + 1]
"""
"""
number >= 1 or <= 8
alpha >= a or <= h

if pawn
    if white 
        number + 1
        alpha + 1 and -1
    if black
        number - 1
        alpha + 1 and -1
        
if knight
    black/white
        if number +1/-1 then alpha +2/-2
        if number +2/-2 then alpha +1/-1

if bishop
    black/white
        if number +1/-1 then alpha +1/-1 until number or alpha goes out of range
        
if rook
    black/white
        if number +/- alpha no change
        if alphe +/1 alpha no change
        until number or alpha goes out of range
        
if queen
    black/white
        rook + bishop
        
if king
    black/white
        number & alpha +1/-1 iterate, excluding current position

"""